#ifndef ALPHA_CONSTANTS_H
#define ALPHA_CONSTANTS_H

#include <stdint.h>

#define ALPHA_PAPER_TRADING_INITIAL_CAPITAL INT64_C(10000000)
#define ALPHA_BACKTEST_COMMISSION_RATE_PCT 0.015
#define ALPHA_BACKTEST_TAX_RATE_PCT 0.18
#define ALPHA_BACKTEST_SLIPPAGE_BPS 3
#define ALPHA_MAX_TICKERS_PER_WS 40
#define ALPHA_MAX_SCREENED_TICKERS 10
#define ALPHA_DEFAULT_COLLECTOR_DAILY_LIMIT 100
#define ALPHA_SCREENER_VOLUME_SURGE_RATIO 2.0
#define ALPHA_SCREENER_CHANGE_PCT_THRESHOLD 3.0

#endif
